### ISSUE TITLE
Unhandled rejection Error: ERR invalid DB index

### ISSUE THREAD

**Issue by habdelra** [LevelbossMike/ember-deploy-redis#13]
When I use ember deploy for cloud redis (a heroku add-on), I get the error that an invalid DB index has been specified. I think we should have the ability to specify the DB index in the config

![screen shot 2015-06-03 at 12 11 29 pm](https://cloud.githubusercontent.com/assets/61075/7965159/b3b519e4-09e9-11e5-8617-381938e475e2.png)

**Comment by LevelbossMike** [comment]
are you using the new version of ember-cli-deploy already? seems like it by the output. The pipeline branch does not work with this addon. There's https://github.com/zapnito/ember-cli-deploy-redis for redis integration into the new pipeline

**Comment by habdelra** [comment]
Yeah I am--thanks!

**Comment by LevelbossMike** [comment]
Ok I am closing this for now then. Please raise issues with the new addon in the respective repository as this is the one that works with the pipeline.
