### ISSUE TITLE
Setting random revision key blows up current revision

### ISSUE THREAD

**Issue by kenips** [LevelbossMike/ember-deploy-redis#14]
hey @LevelbossMike thanks for the amazing project! Just notice another bug that blew up our production env for a bit :'(....

It looks that setting a revision that doesn't exist will continue to set the `manifest:current` key in Redis although proper error message is returned. This really isn't expected base on the message.

Looking at the code it seems like [the promises are chained](https://github.com/LevelbossMike/ember-deploy-redis/blob/master/lib/redis.js#L59) so although the mismatched revision is detected the reject is too late to prevent the code from updating the current revision to the mismatched.

On a greater scheme of things I'm a bit surprised that this logic is implemented at the specific adapter level... I was expecting ember-cli-deploy to implement this check (via adapter's listing revisions capability, of course). Just a thought anyway.

**Comment by LevelbossMike** [comment]
Yes I can confirm this is really a problem. I am currently working on a patch.

Thanks for your input about the listing command. I can't recall why I implemented it this way but you have a good point there

**Comment by LevelbossMike** [comment]
Version 0.0.5 fixes this issue. Thx for reporting this :+1:

**Comment by kenips** [comment]
👍🏻👍🏻 thanks for the quick update!!!
