### ISSUE TITLE
Unable to create an ssh connection through a bastion server

### ISSUE THREAD

**Issue by mbasset** [LevelbossMike/ember-deploy-redis#15]
In our setup the redis server we connect to does not have a public interface. AWS VPC elasticache redis. Therefore we need to connect to it via a bastion server. Unfortunately the ssh connection with this module assumes that the server being connected to is the one that hosts redis. 

We have attempted to make some modifications to the connection tunnel but this results in problems when trying to lookup the host dns name of the redis server which does not have a static IP and relies on the AWS DNS.

```
Trying to upload `dist/index.html`...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:6379 failed - getaddrinfo ENOTFOUND xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    at RedisClient.on_error (/Users/mbasset/Code/next/node_modules/ember-deploy-redis/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/Users/mbasset/Code/next/node_modules/ember-deploy-redis/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:107:17)
    at net.js:950:16
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by tmayr** [comment]
Exactly in the same boat here, managed to get to the same point as you did.

**Comment by LevelbossMike** [comment]
Haven't tried out ssh-tunneling yet but maybe I'll have time to do this on the weekend.

@tim-evans  is using ssh-tunneling and contributed the feature maybe he can jump in?

**Comment by tim-evans** [comment]
Sure! What does your config look like for ssh?

Cf.

``` javascript
store: {
  type: 'redis',
  host: 'staging01.blueboxgrid.com',
  port: 6379,
  ssh: {
    username: 'deploy',
    privateKey: '~/.ssh/id_rsa'
  }
}
```

**Comment by tmayr** [comment]
@tim-evans The configuration looks exactly like yours, but we need to connect to another domain after the tunnel is set (by default it connects to localhost).

**Comment by tim-evans** [comment]
Oh, you need to tunnel a tunnel. Hmmm. The addon can't do that at the moment.

**Comment by mbasset** [comment]
We are looking to do a similiar think also. Something like:

```
  staging: {
    store: {
      host: 'internal.redis.server',
      port: 6379,
      ssh: {
        username: process.env['USER'],
        privateKey: '~/.ssh/id_rsa',
        host: 'bastion.server',
        port: 22
      }
    }
```

**Comment by tim-evans** [comment]
For you brave folks who'd like to implement this, I'd look at https://github.com/LevelbossMike/ember-deploy-redis/blob/master/lib/redis-client.js#L23-L59, which sets up the tunnel.

**Comment by mbasset** [comment]
I looked into that but was unable to get it to resolve the DNS using the tunnel. I'm actually not sure what goes through that tunnel.

**Comment by tmayr** [comment]
After going over how a tunnel is supposed to work and checking the tunnel-ssh lib, its fairly easy to do, we were just missing a param!

```
    store: {
      type: 'redis',
      host: '<redis_ip>,
      port: <redis_port>,
      ssh: {
        username: '<ssh_user>',
        privateKey: '<private_key>',
        dstHost: '<elasticache_redis_endpoint>'
      }
    }
```

**Comment by tim-evans** [comment]
Hooray! Maybe a PR for docs?

**Comment by tmayr** [comment]
#16 Hopefully its all good

**Comment by mbasset** [comment]
Excellent will try that later today!

**Comment by mbasset** [comment]
Humm not able to connect using new settings though that may be related to the our AWS VPC security groups. Will investigate more later.

**Comment by tmayr** [comment]
Can you post what your config ended up being? and are you getting any errors?

**Comment by mbasset** [comment]
I was able to get it to work. It was our security groups. :)
