### ISSUE TITLE
Stash checksum and/or timestamp in Redis

### ISSUE THREAD

**Issue by mwpastore** [LevelbossMike/ember-deploy-redis#21]
It would be fantastic if ember-deploy-redis would also stash a checksum (or the commit SHA) and/or a build date/time (or the commit timestamp) of the index to use in the the `ETag` and `Last-Modified` HTTP headers. Something like: 

```
foo:index:current => '<!DOCTYPE html>...'
foo:index:current:meta => checksum '787b3dd284fd99202adfa4e18a28126d159552c5' 
                          timestamp 'Wed Sep 16 19:28:37 2015 +0200'
```

And then...

``` ruby
require 'sinatra'
require 'redis'

get '/' do
  content_type 'text/html'
  expires 3_600, :public

  redis = Redis.new
  index_key = redis.get("foo:current")
  index_key = "foo:#{params[:index_key]}" if params[:index_key]

  meta = redis.hgetall("#{index_key}:meta")
  etag meta[:checksum]
  last_modified meta[:timestamp]

  redis.get(index_key)
end
```

Stashing the content in the same hash as the metadata would be ideal (to limit the Redis hits) but would break backwards compatibility.

**Comment by LevelbossMike** [comment]
Thanks for opening this issue! This sounds like a useful feature! As this plugin will be superseded by https://github.com/ember-cli-deploy/ember-cli-deploy-redis for the new release of ember-cli-deploy I suggest to open an issue on that repository instead though as this is the one that will be actively maintained in the future.

**Comment by mwpastore** [comment]
Will do!

**Comment by LevelbossMike** [comment]
Closing in favor of https://github.com/ember-cli-deploy/ember-cli-deploy-redis/issues/37
