### ISSUE TITLE
using ssh tunneling with encrypted private key

### ISSUE THREAD

**Issue by danielspaniel** [LevelbossMike/ember-deploy-redis#22]
I am using the ssh option to tunnel into the server for my redis deploys and I get this error:

 "Encrypted private key detected, but no passphrase given"

 This key is encrypted with a passphrase ( so the error is right on ).
 So, I am curious. Are people using unencrypted keys?  Or is there some way to use encrypted key with the redis-deploy ssh option ?

 I could use an unencrypted key .. I suppose .. but do I have to?

**Comment by dcyriller** [comment]
You can achieve so by using the following pattern : 

``` javascript
module.exports = {
    production: {
      buildEnv: 'production',
      store: {
        type: 'redis',
        ssh: {
          username: process.env.USER,
          port: 22,
          host: 'your distant host',
          dstPort: 6379, // redis port
          dstHost: 'localhost', // redis host on server
          passphrase: process.env.SSH_PWD, // passphrase in env var
          privateKey: 'path/to/your/key'
        }
      }
    }
  };
```

**Comment by danielspaniel** [comment]
Really? ok .. that seems so easy .. how did I miss that ? .. is that documented? Will give that a try

**Comment by dcyriller** [comment]
Actually, no, it's not documented. It seems to be a hack as this functionnality is provided by ssh2, underlying package of tunnel-ssh (which is a ember-deploy-redis dependancy).

**Comment by danielspaniel** [comment]
Ok .. thanks .. good tip :)
