### ISSUE TITLE
Mention compatibility with the latest ember-cli-deploy in the README

### ISSUE THREAD

**Issue by rromanchuk** [LevelbossMike/ember-deploy-redis#25]
A lot has changed with `ember-cli-deploy` with their new plugin system, including a new `ember-cli-deploy-redis` which can get pretty confusing with all the documentation decay out there.

**Comment by LevelbossMike** [comment]
Thx for the reminder. I updated the README. Users should definitely consider upgrading to ember-cli-deploy 0.5.x
