### ISSUE TITLE
Changing code of the ember app does not change the checksum for the redis key

### ISSUE THREAD

**Issue by rduque1** [LevelbossMike/ember-deploy-redis#3]
Hi,

I was wondering if this is normal behavior. I did a first ember deploy with the redis adapter and got as keys in my redis:

```
isdb:2207a7b
isdb
```

After I did some changes in my ember app files and wanted to do a deploy again. But then I got:

```
Trying to upload `dist/index.html`...
Upload failed!

Did you try to upload an already uploaded revision?

Please run `ember deploy:list` to investigate.
```

The redis keys are the same: 

```
isdb:2207a7b
isdb
```

But the html for the key isdb:2207a7b is the latest, so it did upload but on the same key.
But I would have expect that another checksum would have been generated and having in my redis the following keys:

```
isdb:2207a7b
isdb:new-checksum
isdb
```

Is the checksum not generated from the dist/index.html? Because there is an difference between the old and new dist/index.html.

Thank you for the help,

Robin

**Comment by rduque1** [comment]
Never mind, i should have read more it is based on the git sha.
Sorry for bothering and thanks for the great projects you contributing.

**Comment by trucam** [comment]
So what's the plan if you don't want to make a new commit just to deploy?

**Comment by LevelbossMike** [comment]
It does not make much sense to do a new deployment if you have not changed anything. This is something that occurs mostly in development scenarios and even there that's mostly an edge case but shouldn't be that much of an issue if you are really deploying to production/staging.

The new release of ember-cli-deploy will support forcing an update with the new pipeline approach though.
