### ISSUE TITLE
Allow for configuration of redis connection via URL

### ISSUE THREAD

**Issue by lukemelia** [LevelbossMike/ember-deploy-redis#6]
We should be able to provide a URL in configuration connection to redis. It is supported by then-redis, so it shouldn't be too much work to support it in this library. Developers commonly have connection info available as a URL (from an env var, for example), and they shouldn't have to write code to parse it out.

**Comment by LevelbossMike** [comment]
This is actually already supported but not documented. You just have to pass the url as a string instead of a configuration object to the store property of the respective environment.

**Comment by jamesdixon** [comment]
Just to confirm, you pass the connection string directly to store? Also, what is the format of the connection string that's accepted? I've tried a few different versions with no success. Thank you!

**Comment by backspace** [comment]
I tried this: `production: {store: 'redis://…'}` and it worked, though it produced this error:

```
Unhandled rejection Error: ERR invalid DB index
```

**Comment by lukemelia** [comment]
@backspace I believe that error is from how then-redis parses the url. Some redis providers include dummy username (after the `//` and before the `:`) that you will want to remove or replace with a numeric database index.

**Comment by backspace** [comment]
Ah, thanks. With just `redis://password@host:port` it failed totally, but it worked with `redis://0:password@host:port`. I can make a PR to update the README, but I’m new to Redis and don’t understand the implications of specifying a database index like that. When I used a configuration object with its `host`, `port`, and `password`, I didn’t specify an index; was it just choosing `0` by default?

**Comment by backspace** [comment]
Never mind, I see that it [does choose 0 by default](https://github.com/mjackson/then-redis/blob/master/Client.js#L49).
